### ISSUE TITLE
[P1] Uninstall with Script should not throw errors

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#152]
Not critical, not urgent, but  Uninstall with Script should not throw errors.

It should be handled consistently with no errors.

<img width="1089" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/ead0e4d1-7224-4893-a980-378c397e947c">

**Comment by virubiotor** [comment]
Fixed in #ef2a4ed

**Comment by CESARDELATORRE** [comment]
OK, closing then.

**Comment by CESARDELATORRE** [comment]
Re-opening it. IT still throws errors in the latest version I just tested:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/c156388f-e75a-4be0-b4c3-253674e468dd)

**Comment by virubiotor** [comment]
It was a race condition between the delete namespace and the other resources, I have change it so that we only delete the namespace and recursively all its resources. Fixed in 57d354d

**Comment by CESARDELATORRE** [comment]
This is fixed now. :)

<img width="935" alt="image" src="https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/6ae258f1-2e8f-48ac-b604-0702578f2846">
