### ISSUE TITLE
[P0] [BUG] Control Plane app cameras dasboard not working with Xingtera 5G camera

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/mec-app-solution-accelerator#97]
Control Plane app cameras dasboard not working with Xingtera 5G camera

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/719bb802-5f00-4290-8acc-a19fb64c91b5)

The RTSP is using an IP from the 5G network:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/8e4eb0ca-78ff-4a1b-a8f3-fcaf08f1c71b)

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/eaa31d9c-ab8a-4e94-8b0f-e0ac1897a65c)

**Comment by CESARDELATORRE** [comment]
I created a RTSP container which works with the MEC-Accelerator, but it's not working now in the "cameras dashboard", neither:

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/0eec38ed-cdb7-4104-b137-8f49220a90fe)

Works in MEC-Accelerator:
![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/01b4480a-cac1-41cc-8247-51961f3c8079)

It does NOT work in the dashboard even refreshing, F5 in browser, etc.

![image](https://github.com/Azure/mec-app-solution-accelerator/assets/1712635/c824fdb3-39c4-4fd9-acb0-e91f11c1ee73)

**Comment by 3lcarry** [comment]
Fixed with the latest RTSPConverter image, working on a player for the flv stream

**Comment by CESARDELATORRE** [comment]
Still NOT working, at least in the k3s in the VM.

See related BUG that I created today:
https://github.com/Azure/mec-app-solution-accelerator/issues/120

**Comment by CESARDELATORRE** [comment]
Fixed! Closed!
